version: '3.8'

services:
  web:
    build: .
    command: python app/main.py
    volumes:
      - .:/app/
    ports:
      - ${DEV_PORT}:${DEV_PORT}
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:alpine3.17

  postgres:
    image: postgres:alpine3.17
    environment:
      - POSTGRES_USER= ${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}


